### ISSUE TITLE
如何往一个已经存在的bucket里面丢文件

### ISSUE THREAD

**Issue by lousaibiao** [cuiliang/Cuiliang.AliyunOssSdk#4]
如果需要往一个已经存在的bucket里面put文件,是不是要先Listbuckets,然后比如根据名字筛选出特定的bucket,然后把这个bucketinfo作为PutObjectAsync的参数来往这个bucket里面丢数据.

**Comment by cuiliang** [comment]
@lousaibiao 往哪个bucket里存，肯定要事先知道的吧。
