### ISSUE TITLE
怎样释放OssClient ？

### ISSUE THREAD

**Issue by xiaoquisme** [cuiliang/Cuiliang.AliyunOssSdk#6]
看到java版SDK有_client.shutdown()。在这里找不到对应的方法。能否告知怎么样释放呢？

**Comment by cuiliang** [comment]
这个和java版本没关系的

**Comment by xiaoquisme** [comment]
非常感谢 ，当时我用我cnblogs fork 过去的，然后出现了httpclient 无法释放的问题 https://github.com/cnblogs/Cuiliang.AliyunOssSdk/pull/1 我以为是ossclient没有释放的问题

**Comment by cuiliang** [comment]
刚merge了cnblogs的代码。 现在HttpClient是单例的了，没有每次new。
